### ISSUE TITLE
Arduino IDE - 'showString' was not declared in this scope

### ISSUE THREAD

**Issue by MikeBookham** [openenergymonitor/emonth2#10]
Using the Arduino IDE on Ubuntu 20.10 an error with '**showString’** was not declared in this scope was encountered within **master/firmware/src/src.ino**
The solution is to add:
`static void showString(PGM_P s);`

**Comment by SlyRemarks** [comment]
Thank you, @MikeBookham. I'm so sorry your comment was overlooked for so long.

The line `static void showString(PGM_P s);` has been included in the latest release, V3.2.6.
