### ISSUE TITLE
Custom encryption key

### ISSUE THREAD

**Issue by jonathandreyer** [openenergymonitor/emonth2#15]
Hello, I have implemented an option to build the firmware with a custom encrypted key. It is possible to see the modification [here](https://github.com/jonathandreyer/emonth2/commit/e47dab44f89eb157c9354e1c88b631e73db9302b). Are you interested to integrate it into the repository?
Best regards,
Jonathan Dreyer

**Comment by TrystanLea** [comment]
Thanks @jonathandreyer yes happy to merge

**Comment by jonathandreyer** [comment]
It is a pleasure @TrystanLea . I have created the linked PR.

Maybe, a cleanup of the code will be useful. When I save the code, some IDE (like VS code or Atom), remove excess space automatically. It will also be nice to have the CI to automatically build the firmware (to each commit) to be sure, there is no compilation error.
