### ISSUE TITLE
DIP adjusted nodeID not being used when using LPL radio format

### ISSUE THREAD

**Issue by greeebs** [openenergymonitor/emonth2#18]
https://github.com/openenergymonitor/emonth2/blob/e836d42bd4eac74fb98b36637aa6992f8c338fd5/firmware/emonth2.ino#L257

Should this line use "nodeID" instead of "EEPROM.nodeID"?

See: https://community.openenergymonitor.org/t/emonth-2-with-3-external-probes-nothing-received/24133/19

**Comment by glynhudson** [comment]
Thanks, this has been fixed by https://github.com/openenergymonitor/emonth2/commit/8c13786c70e0dcced7f3c87a8846602e7b9ce7dc
