### ISSUE TITLE
Missing equality comparison operator = vs == ?

### ISSUE THREAD

**Issue by stuartpittaway** [openenergymonitor/emonth2#19]
Is this line missing a "==" ?

https://github.com/openenergymonitor/emonth2/blob/6fd6c33de937796cbab35581ffa917428765a2b6/firmware/emonth2_config.ino#L160

**Comment by glynhudson** [comment]
No, this is correct. It's setting `pass_result` to the return of `getPass()` and then evaluating `pass_result`. 

I guess, it could be split into two lines to make to clearer, but it functions as intended.

**Comment by stuartpittaway** [comment]
Ok, no problem.  The C++ code linter picked it up as a warning/typo.
