### ISSUE TITLE
Calibration mode entry timeout of 2 seconds is too short (v4.1.5)

### ISSUE THREAD

**Issue by nmcgann** [openenergymonitor/emonth2#21]
It is very tricky to type all the characters required to enter calibration mode within 2 seconds. I am using Putty on a PC so it means typing +, + , +, control-shift-m, control-shift-j (with the + characters requiring a shift too on my laptop keyboard). 

[note: unmodified Putty does not have a way of sending \r\n in a single keystroke]

The original 5 seconds would be much easier, I can do it in 4 without having to do anything special like leaving a finger pressing the shift key down.

**Comment by glynhudson** [comment]
I agree, I've increased the delay to 4s. This should be enough time
