### ISSUE TITLE
Firmware upload tool

### ISSUE THREAD

**Issue by Deathlesss** [openenergymonitor/emonth2#3]
Hi,

I was about to do something about the firmware (beginner here), and found out here https://github.com/openenergymonitor/emontx-3phase That an [upload](https://github.com/openenergymonitor/emonupload) tool exist here. Perhaps good to update the introduction text for those looking to update the emonTH?

Thanks,

**Comment by glynhudson** [comment]
Sure good idea

**Comment by glynhudson** [comment]
Readme has been updated with a link to the upload tool
