### ISSUE TITLE
Initial values always Zero

### ISSUE THREAD

**Issue by pb66** [openenergymonitor/emonth2#4]
Upon (re)inserting batteries the first payload is always all zeros (except pulse count which is always 1).

I haven't looked into this thoroughly yet, just making a note here at this stage for future investigation.

Either the settle time to the first packet needs extending, the first payload needs to be discarded or the order of events changed so only a properly populated payload is sent.

A zero temperature reading is often a valid temperature reading so a 0°C value should never be sent unless it is a true reading, this is why we moved to out of range 300°C error codes.

Plus there should never be an instance where 0v battery voltage is recorded, if the battery voltage was truly 0v, how was the data sent?

**Comment by glynhudson** [comment]
Agree it will be best if this did not happen. A warm up. Should be defined to allow the unit 
 settle before posting it's first values. I wonder if you're picking up the rf factory test packets

**Comment by jonathandreyer** [comment]
Hi everyone, I have been using an emonth2 with emoncms from several years.
If you are interested, I can try to fix this bug. However, I don't know your RF factory test packets. Is it necessary to send zero value or we can send (as a test) real value?

**Comment by SlyRemarks** [comment]
Fixed in latest release, V3.2.6. Factory test now uses network group 1.
