### ISSUE TITLE
Node ID

### ISSUE THREAD

**Issue by Deathlesss** [openenergymonitor/emonth2#5]
Hi,

I tried to upload the firmware myself with the programmer and change dhe Node ID in the src.ino. So the first one went ok, ID 30.

The second one should have been ID 25. But when I uploaded it, it became ID 27. Unknown to me I realised (after a while) that the DIP switches are set from ID 23 to 26. We inherited the emonTH which was already ID 25 before, so the DIP switches were set for that, so when one set the ID to 25 in the firmware (instead of leaving it at ID 23) the resulting ID becomes +2.

It would have been clearer if this was mentioned in the comments of the firmware after the Node ID line in the src.ino, line 84. It would be also helpful if there is a guideline which numbers one can use, the wiki says up to 30 emonTH, but now I wonder which NodeIDs are those that we can set manually via firmware (it seems that one should use 23, 24, 25, 26 for manual node ID settings).

Perhaps it should be mentioned in the wiki that node changes can be done with firmware updates.
https://wiki.openenergymonitor.org/index.php/EmonTH_V1.5#DIP_Switch_node_ID

Thanks!

**Comment by glynhudson** [comment]
Thanks for your feedback we would accept any pull requests with extra comments to clarify this.
