### ISSUE TITLE
Adding sd card

### ISSUE THREAD

**Issue by jsqu4re** [openenergymonitor/emonth2#9]
Hi! This looks like a really cool project! Do you feel it is simple to add an sd card to the emonth2 or are the required pins not available on the board?

**Comment by glynhudson** [comment]
Thanks. It should be possible, however the SD card connects vis SPI as does the RFM69CW. It's possible to have multiple SPI devices on the same bus, you will just need to handle the slave select lines. Let us know how you get on. I would recommend posting on our community forum, someone may have done this before: https://community.openenergymonitor.org/

**Comment by jsqu4re** [comment]
Thanks for the quick answer!!
